name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run checks and tests
        run: just check
